import {VersionInterface} from "./version-interface";

export interface ModuleInterface {
    id?: string;
    dependent_repos_count: number;
    dependents_count: number;
    deprecation_reason: string | null;
    description: string;
    forks: number;
    homepage: string;
    keywords: string[];
    language: string;
    latest_download_url: string;
    latest_release_number: string;
    latest_release_published_at: string;
    latest_stable_release_number: string;
    latest_stable_release_published_at: string;
    license_normalized: boolean;
    licenses: string;
    name: string;
    normalized_licenses: string[];
    package_manager_url: string;
    platform: string;
    rank: number;
    repository_license: string;
    repository_url: string;
    stars: number;
    status: string | null;
    versions: VersionInterface[];
};